name: venvCB
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=13.0.85
  - cuda-runtime=12.4.1
  - cuda-version=13.0
  - dav1d=1.2.1
  - et_xmlfile=2.0.0
  - expat=2.7.1
  - ffmpeg=4.2.2
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2023.0.0
  - jinja2=3.1.6
  - jpeg=9f
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libavif=1.1.1
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.15.1.6
  - libcurand=10.4.0.35
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnvfatbin=13.0.85
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopus=1.3.1
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.7.3
  - networkx=3.4.2
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.0.17
  - pcre2=10.42
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.18
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - readline=8.3
  - requests=2.32.5
  - sqlite=3.50.2
  - tbb=2021.8.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - x264=1!157.20191217
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - anykeystore==0.2
      - apex==0.9.10.dev0
      - args==0.1.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - av==15.1.0
      - beautifulsoup4==4.13.5
      - bitsandbytes==0.47.0
      - blobfile==3.1.0
      - braceexpand==0.1.7
      - cachetools==5.5.2
      - certifi==2026.1.4
      - click==8.3.1
      - clint==0.5.1
      - clip==1.0
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - contourpy==1.3.2
      - cryptacular==1.6.2
      - cycler==0.12.1
      - datasets==4.1.1
      - decorator==5.2.1
      - decord==0.6.0
      - deepspeed==0.17.6
      - defusedxml==0.7.1
      - diffusers==0.35.1
      - dill==0.4.0
      - distro==1.9.0
      - dm-tree==0.1.9
      - easydict==1.13
      - einops==0.8.1
      - einops-exts==0.0.4
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fairscale==0.4.13
      - filelock==3.20.3
      - fire==0.4.0
      - flash-attn==2.5.8
      - flatbuffers==25.12.19
      - fonttools==4.60.0
      - frozenlist==1.7.0
      - fsspec==2026.1.0
      - ftfy==6.3.1
      - func-timeout==4.3.5
      - fvcore==0.1.5.post20221221
      - gast==0.7.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.40.3
      - google-genai==1.2.0
      - google-pasta==0.2.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hjson==3.1.0
      - hpsv2==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hupper==1.12.1
      - icecream==2.1.8
      - idna==3.11
      - imageio==2.31.1
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - iopath==0.1.10
      - jax==0.6.2
      - jaxlib==0.6.2
      - jiter==0.11.0
      - joblib==1.5.2
      - keras==3.12.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - librosa==0.10.1
      - llava==1.7.0.dev0
      - llvmlite==0.45.0
      - lxml==6.0.1
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - moviepy==2.2.1
      - msgpack==1.1.1
      - multidict==6.6.4
      - multiprocess==0.70.16
      - namex==0.1.0
      - ninja==1.13.0
      - nltk==3.9.1
      - numba==0.62.0
      - numpy==2.2.6
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - open-clip-torch==3.1.0
      - openai==1.108.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.18.0
      - oryx==0.2.9
      - packaging==26.0
      - pandas==2.3.2
      - parameterized==0.9.0
      - pastedeploy==3.1.0
      - pbkdf2==1.3
      - peft==0.5.0
      - pillow==10.0.0
      - plaster==1.1.2
      - plaster-pastedeploy==1.0.1
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - proglog==0.1.12
      - propcache==0.3.2
      - protobuf==6.33.5
      - psutil==5.9.5
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocoevalcap==1.2
      - pycocotools==2.0.10
      - pycryptodomex==3.23.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.4
      - pyramid==2.0.2
      - pyramid-mailer==0.15.1
      - pytest==7.2.0
      - pytest-split==0.8.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python3-openid==3.2.0
      - pytorchvideo==0.1.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - qwen-vl-utils==0.0.11
      - regex==2026.1.15
      - repoze-sendmail==4.4.1
      - requests-oauthlib==2.0.0
      - rich==14.3.1
      - rouge-score==0.1.2
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.38.0
      - setuptools==80.9.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soupsieve==2.8
      - soxr==1.0.0
      - sqlalchemy==2.0.43
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-probability==0.25.0
      - termcolor==2.4.0
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - timm==1.0.19
      - tokenizers==0.21.4
      - tomli==2.2.1
      - torchcodec==0.1.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transaction==5.0
      - transformers==4.51.3
      - translationstring==1.4
      - typer-slim==0.21.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uvicorn==0.35.0
      - velruse==1.1.1
      - venusian==3.1.1
      - wandb==0.22.0
      - wcwidth==0.2.13
      - webdataset==1.0.2
      - webob==1.8.9
      - websockets==14.2
      - werkzeug==3.1.5
      - wrapt==2.0.1
      - wtforms==3.2.1
      - wtforms-recaptcha==0.3.2
      - xformers==0.0.29.post1
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.20.1
      - zipp==3.23.0
      - zope-deprecation==6.0
      - zope-interface==8.0
      - zope-sqlalchemy==4.0
prefix: /home/fi513841/miniconda/envs/venvCB
